[package]
name = "railwindcss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.6.0"
swc_css = "0.125.10"
swc_common = "0.28.8"
swc_atoms = "0.4.15"